### ISSUE TITLE
Brew Installed in a different location

### ISSUE THREAD

**Issue by RogerHuba** [codefellows/setup-guide#137]
Nighttime 102 student had brew installed in the following directory:

/usr/local/bin/brew/

instead of 

/opt/homebrew/bin/

Gave errors in adding path to .zprofile.

**Comment by brookr** [comment]
I don't think this PR will work, because `which brew` would only return a result if `brew` is in the PATH... and adding `brew` to the PATH is what this line is trying to do.

I tested this on a fresh brew install for Linux, and `which brew` returns nothing (but sounds cool ;) ).

Was this tested on a fresh macOS install to verify that `which brew` would find something, before the PATH is updated?

**Comment by johncokos** [comment]
(wonders aloud) ... if you `reset` your shell before running that command, your path would be updated and then which should work, correct?

That command does a whole bunch of other stuff and it needs to know where brew is first.

Maybe that's the ticket there, running reset after each of these commandds that we have them do

**Comment by brookr** [comment]
Speaking of the path not getting updated correctly, a partner-school reported that a WSL student has the same problem of `brew not found` when re-opening the terminal, and claims this was the fix: 

https://stackoverflow.com/questions/64680855/how-to-install-homebrew-on-windows-wsl-ubuntu-and-fix-zsh-brew-command-not-fo

**Comment by johncokos** [comment]
We can force feed that into .profile bit that gets done earlier ... but I'm still honking the "no more wsl" horn

**Comment by johncokos** [comment]
At a minimum, let's add those commands to the "if it goes wrong" section of that page
