### ISSUE TITLE
The curl command for the .profile causing display and command issues

### ISSUE THREAD

**Issue by RogerHuba** [codefellows/setup-guide#25]
Mac setup:
curl -s https://raw.githubusercontent.com/codefellows/setup-guide/master/configs/.profile >> ~/.profile

This is where it broke for students.  Caused multi line display with no color and a lot of special characters over 3-5 lines.  Also caused problems with commands being recognized.

**Comment by johncokos** [comment]
@brook had asked me to put all of the "new stuff" like aliases, variables, etc into `~.profile` since most shells read this already. 

I suggested making a new file instead, called `~.settings` or something like that and then having `.bashrc` or `.zshrc` do a `source ~/.settings` or whatever to get the stuff custom to our installation in.

I think we need to revisit that earlier decision as doing it in a separate file can be easily unwound and re-done without harming the core files in the login process.

**Comment by RogerHuba** [comment]
The .profile is still running into issues.  Mac students are unable to load NVM unless we change the .profile to include this

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

The PS1 also appears to be incorrect as it is leaving students with (see image)
<img width="651" alt="Screen Shot 2020-07-22 at 17 56 30" src="https://user-images.githubusercontent.com/38219102/88249083-277e5300-cc58-11ea-8db7-92aaf90636fe.png">

**Comment by bnates** [comment]
@johncokos can you check this out, make a fix, and give us your thoughts/implement?

**Comment by JB-Tellez** [comment]
I'm having behavior on Ubuntu 18 that is likely related...
The only way I could be 'nvm install' to work was. by running 'source ~/.profile' each time.

**Comment by JB-Tellez** [comment]
Doesn't work on MacOS due to linux_brew paths in downloaded .profile

This works in .zshrc ...
> source $(brew --prefix nvm)/nvm.sh

**Comment by JB-Tellez** [comment]
Fixed by #31 IMHO. Roger, if you agree please close.

**Comment by RogerHuba** [comment]
Issue to be closed and fixed.
